[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nr-urlcc-phy-sim"
version = "0.1.0"
description = "Minimal NR-URLLC PHY simulator (M0–M1)"
requires-python = ">=3.9"
